name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # change if you use a different branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create env file
        run: |
          echo "${{ secrets.STAGING_B64 }}" | base64 -d > .env

      - name: Verify .env exists
        run: |
          if [ -s .env ]; then
            echo ".env created successfully"
            head -n 3 .env | sed 's/=.*/=*** (redacted)/'
          else
            echo ".env file is empty!"
            exit 1
          fi

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # change if your output folder is different
